# COLORS #
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (220, 0, 0)
GREEN = (0, 220, 0)
GRAY = (100, 100, 100)

# WINDOW SETTINGS #
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
WINDOW_BACKCOLOR = WHITE
TILE_SIZE = 15
FPS = 10

# BOARD SETTINGS#
BOARD_X = 10 * TILE_SIZE
BOARD_Y = 5 * TILE_SIZE
BOARD_ROWS = 30
BOARD_COLS = 30
BOARD_WIDTH = BOARD_ROWS * TILE_SIZE
BOARD_HEIGHT = BOARD_COLS * TILE_SIZE
BOARD_COLOR = GRAY
BOARD_THICKNESS = 1

# SNAKE SETTINGS#
SNAKE_SPEED = 1 * TILE_SIZE
SNAKE_COLOR = BLACK

# APPLE SETTINGS #
APPLE_RADIUS = TILE_SIZE // 2
APPLE_COLOR = GREEN

# TEXT SETTINGS #
FONT_SIZE = 25
SCORE_PTS_INCREASE = 10
