# COLORS #
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (200, 0, 0)
LIGHT_RED = (255, 0, 0)
GREEN = (0, 180, 0)
LIGHT_GREEN = (0, 240, 0)
BLUE = (0, 0, 220)
LIGHT_BLUE = (0, 0, 255)
GRAY = (100, 100, 100)

# WINDOW SETTINGS #
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
WINDOW_BACKCOLOR = WHITE
TILE_SIZE = 16
FPS = 10

# BOARD SETTINGS#
BOARD_X = 10 * TILE_SIZE
BOARD_Y = 5 * TILE_SIZE
BOARD_ROWS = 30
BOARD_COLS = 30
BOARD_WIDTH = BOARD_ROWS * TILE_SIZE
BOARD_HEIGHT = BOARD_COLS * TILE_SIZE
BOARD_COLOR = BLACK
BOARD_THICKNESS = 1

# STATES SETTINGS #
STATES_X = 10 * TILE_SIZE
STATES_Y = 2 * TILE_SIZE

# SNAKE SETTINGS#
SNAKE_SIZE = 16
SNAKE_SPEED = 1 * TILE_SIZE
SNAKE_COLOR = GREEN
SNAKE_INIT_LENGTH = 4

# APPLE SETTINGS #
APPLE_SIZE = 16
APPLE_COLOR = RED

# TEXT SETTINGS #
SMALL_FONT = 16
MEDIUM_FONT = 24
BIG_FONT = 32
FONT_FAMILY1 = 'Arial'

# SCORE SETTINGS #
SCORE_PTS_INCREASE = 10

# IMAGES #
SNAKE_HEAD_IMG = 'snake_head.png'
APPLE_IMG = 'apple.png'

# TIMING #
GAME_OVER_DELAY = 2
